### ISSUE TITLE
Fatal error

### ISSUE THREAD

**Issue by christian1432** [hcgcloud/pterodactyl-sdk#1]
Hello,
when I use the sdk I get the following issue:

Fatal error: Uncaught Error: Call to undefined function HCGCloud\Pterodactyl\array_add() in /var/www/XXXX/XXXXXX.de/XX.XXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php:89 Stack trace: #0 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php(21): HCGCloud\Pterodactyl\Pterodactyl->request('GET', 'api/application...') #1 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/Actions/ManagesUsers.php(18): HCGCloud\Pterodactyl\Pterodactyl->get('api/application...') #2 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/test.php(4): HCGCloud\Pterodactyl\Pterodactyl->users() #3 {main} thrown in /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php on line 89

Can you help?

**Comment by tyson239** [comment]
Could you please provide the code that cause this error?

**Comment by tyson239** [comment]
I've check the code, it seems that I forgot to add a package whch provides array_add function to composer.json.
**Please check if your project have `illuminate/support` installed. If not, run `composer require illuminate/support`.**
I will fix this issue later, thank you for your feedback. If there's still have problems, feel free to reply.

**Comment by christian1432** [comment]
Hello,
get users and servers are perfect.

CreateUser and CreateServer are the following issues:

Fatal error: Uncaught HCGCloud\Pterodactyl\Exceptions\ValidationException: The given data failed to pass validation. in /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php:110 Stack trace: #0 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php(95): HCGCloud\Pterodactyl\Pterodactyl->handleRequestError(Object(GuzzleHttp\Psr7\Response)) #1 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php(33): HCGCloud\Pterodactyl\Pterodactyl->request('POST', 'api/application...', Array) #2 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/Actions/ManagesUsers.php(52): HCGCloud\Pterodactyl\Pterodactyl->post('api/application...', Array) #3 /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/test.php(5): HCGCloud\Pterodactyl\Pterodactyl->createUser(Array) #4 {main} thrown in /var/www/vhosts/XXXXXX.de/test.XXXXXX.de/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php on line 110

**Comment by christian1432** [comment]
I used this code:

$server = $pterodactyl->createServer([
    "external_id" => "4",
    "name" => "APITest",
    "user" => 1,
    "egg" => 15,
    "pack" => 0,
    "docker_image" => "hub.tencentyun.com/unihc/pterodactyl_images:vcmp",
    "environment" => [
        //Not confirmed
        [
            "server_id" => "",
            "variable_id" => "",
            "variable_value" => ""
        ]
    ],
    "skip_scripts" => false,
    "limits" => [
        "memory" => 64,
        "swap" => 0,
        "disk" => 64,
        "io" => 500,
        "cpu" => 0
    ],
    "feature_limits" => [
        "databases" => 0,
        "allocations" => 0
    ],
    "startup" => "./mpsvrrel64 -port {{SERVER_PORT}}",
    "description" => "test description",
    "node_id" => 1,
    "nest_id" => 5,
    "allocation" => [
        "default" => "16",
        "additional" => [
            "17",
            "18"
        ]
    ]
]);


and


$user = $pterodactyl->createUser([
    "external_id" => "2",
    "email" => 'test@test.com',
    "username" => 'TestUser',
    "first_name" => 'Test',
    "last_name" => 'User',
    "language" => 'zh-cn',
    "password" => '123456'
]);

**Comment by tyson239** [comment]
Make sure you have changed the example code correctly, and some parameters are optional. You can find out example from this unofficial document. https://deploys.io/docs/api/pterodactyl/v1/#create-user
You can just try this to create a user:
```
$user = $pterodactyl->createUser([
"email" => 'test@test.com',
"username" => 'TestUser',
"first_name" => 'Test',
"last_name" => 'User',
"password" => '123456'
]);
```

**Comment by tyson239** [comment]
For create a server, you should also replace those parameters to suit your panel, like 'user', 'egg', 'node_id', 'nest_id'. These id can be found in your panel.

**Comment by christian1432** [comment]
Create Users are fine but when I create a server the error came again.

**Comment by tyson239** [comment]
what parameters have you changed?

**Comment by christian1432** [comment]
I have the following command:

$server = $pterodactyl->createServer([
    "name" => "APITest",
    "user" => 3,
	"nest_id" => 2,
	"node_id" => 1,
    "egg" => 7,
    "limits" => [
        "memory" => 64,
        "swap" => 0,
        "disk" => 64,
        "io" => 500,
        "cpu" => 0
    ],
    "feature_limits" => [
        "databases" => 0,
        "allocations" => 0
    ]
]);

**Comment by tyson239** [comment]
"allocation" => [
"default" => "16",
"additional" => [
"17",
"18"
]

should be also provided, which is your node allocations. ID seems could not be got in frontend, you can check it in database or use API.

**Comment by christian1432** [comment]
Hello,
can you send me an example which all parameters to create an minecraft server?
Thank you :)

**Comment by tyson239** [comment]
@christian1432 you should replace those ids in sample code to yours. It's depend on your own panel.
We have developed a internal version of the sdk to do these stuff conveniently, and will be release soon.

**Comment by christian1432** [comment]
Hello,
do you know which date it will be release

**Comment by FrancoBM12** [comment]
hey

**Comment by FrancoBM12** [comment]
I need help, I get an error when creating a server. This is the code I use:

$ server = $ pterodactyl-> createServer ([
     "external_id" => "4",
     "name" => "APITest",
     "user" => 1,
     "egg" => 3,
     "pack" => 0,
     "docker_image" => "quay.io/pterodactyl/core:java-glibc",
     "environment" => [
         [
             "server_id" => "",
             "variable_id" => "",
             "variable_value" => ""
         ]
     ],
     "skip_scripts" => false,
     "limits" => [
         "memory" => 64,
         "swap" => 0,
         "disk" => 64,
         "io" => 500,
         "cpu" => 0
     ],
     "feature_limits" => [
         "databases" => 0,
         "allocations" => 0
     ],
     "startup" => "java -Xms128M -Xmx {{SERVER_MEMORY}} M -jar {{SERVER_JARFILE}}",
     "description" => "test description",
     "deploy" => [
         "locations" => [1],
         "dedicated_ip" => false,
         "port_range" => []
     ],
     "start_on_completion" => true
]);

**Comment by tyson239** [comment]
@xFrancoBM
try this minfied one, which is used in our production.
the ```$pack``` would be an array with validate rules below:
```php
$rule = [
	'egg' => 'require|number',
	'nest' => 'require|number',
	'databases' => 'require|number',
	'allocations' => 'require|number',
	'memory' => 'require|number',
	'swap' => 'require|number',
	'disk' => 'require|number',
	'cpu' => 'require|number',
	'io' => 'require|number'
];
```
Then use the ```$pack``` to get the egg info.
```php
$egg = $pterodactyl->egg($pack['nest'], $pack['egg']);
```
and use the egg info in the ```createServer```.
```php
$server = $pterodactyl->createServer([
	"external_id" => $external_id,
	"name" => $svr_name,
	"user" => $user['id'],
	"egg" => $pack['egg'],
	"pack" => 0,
	"docker_image" => $egg->dockerImage,
	"skip_scripts" => false,
	"environment" => [],
	"limits" => [
		"memory" => $pack['memory'],
		"swap" => $pack['swap'],
		"disk" => $pack['disk'],
		"io" => $pack['io'],
		"cpu" => $pack['cpu']
	],
	"feature_limits" => [
		"databases" => $pack['databases'],
		"allocations" => $pack['allocations']
	],
	"startup" => $egg->startup,
	"description" => "-",
	"deploy" => [
		"locations" => [$node_id],
		"dedicated_ip" => false,
		"port_range" => []
	],
	"start_on_completion" => true
]);
```

**Comment by tyson239** [comment]
@christian1432 
I am sorry that I saw your reply just now. Just like this sdk, the new version we are working on is also not yet integrated. We plan to consider releasing after everything has been completed.

**Comment by FrancoBM12** [comment]
Well, I didn't quite get it.

**Comment by FrancoBM12** [comment]
Can you help me, please?

**Comment by tyson239** [comment]
Could you provide the error message you encountered?

**Comment by FrancoBM12** [comment]
That's the mistake that comes to me. https://cdn.discordapp.com/attachments/122900397965705216/597208684841533441/unknown.png

**Comment by tyson239** [comment]
Are you using Spigot egg? Try to set the environment variables:
```php
     "environment" => [
		"SERVER_JARFILE" => "server.jar",
		"DL_VERSION" => "latest",
		"DL_PATH" => ""
     ]
```

**Comment by FrancoBM12** [comment]
So to this: I'll add the code you passed me?
```$ server = $ pterodactyl-> createServer ([
     "external_id" => "4",
     "name" => "APITest",
     "user" => 1,
     "egg" => 3,
     "pack" => 0,
     "docker_image" => "quay.io/pterodactyl/core:java-glibc",
     "environment" => [
		"SERVER_JARFILE" => "server.jar",
		"DL_VERSION" => "latest",
		"DL_PATH" => ""
     ],
     "skip_scripts" => false,
     "limits" => [
         "memory" => 64,
         "swap" => 0,
         "disk" => 64,
         "io" => 500,
         "cpu" => 0
     ],
     "feature_limits" => [
         "databases" => 0,
         "allocations" => 0
     ],
     "startup" => "java -Xms128M -Xmx {{SERVER_MEMORY}} M -jar {{SERVER_JARFILE}}",
     "description" => "test description",
     "deploy" => [
         "locations" => [1],
         "dedicated_ip" => false,
         "port_range" => []
     ],
     "start_on_completion" => true
]);

**Comment by tyson239** [comment]
```php
$server = $pterodactyl-> createServer([
	"external_id" => "4",
	"name" => "APITest",
	"user" => 1,
	"egg" => 3,
	"pack" => 0,
	"docker_image" => "quay.io/pterodactyl/core:java-glibc",
	"environment" => [
		"SERVER_JARFILE" => "server.jar",
		"DL_VERSION" => "latest",
		"DL_PATH" => ""
	],
	"skip_scripts" => false,
	"limits" => [
		"memory" => 64,
		"swap" => 0,
		"disk" => 64,
		"io" => 500,
		"cpu" => 0
	],
	"feature_limits" => [
		"databases" => 0,
		"allocations" => 0
	],
	"startup" => "java -Xms128M -Xmx {{SERVER_MEMORY}} M -jar {{SERVER_JARFILE}}",
	"description" => "test description",
	"deploy" => [
		"locations" => [1],
		"dedicated_ip" => false,
		"port_range" => []
	],
	"start_on_completion" => true
]);
```

**Comment by FrancoBM12** [comment]
This page doesn't work, that comes out

**Comment by FrancoBM12** [comment]
Where's the nest going?

**Comment by tyson239** [comment]
The nest id of your eggs, check `admin/nests`.
![image](https://user-images.githubusercontent.com/5617150/60779196-579da580-a16c-11e9-8679-503df7187e2c.png)

**Comment by FrancoBM12** [comment]
I mean the api, where do I put the id of the nest?

**Comment by tyson239** [comment]
It is not necessary, unless you use the ```$pterodactyl->egg();``` to reuse some variables to create server.

**Comment by FrancoBM12** [comment]
So, why do not you let me create a server?

**Comment by tyson239** [comment]
try this one, tested just now for Spigot eggs.
```php
$egg = $pterodactyl->egg(1, 3);
$server = $pterodactyl->createServer([
	"name" => "test",
	"user" => 1,
	"egg" => 3,
	"pack" => 0,
	"docker_image" => $egg->dockerImage,
	"skip_scripts" => false,
	"environment" => [
		"SERVER_JARFILE" => "server.jar",
		"DL_VERSION" => "latest",
		"DL_PATH" => ""
	],
	"limits" => [
		"memory" => 2048,
		"swap" => 0,
		"disk" => 2048,
		"io" => 100,
		"cpu" => 0
	],
	"feature_limits" => [
		"databases" => 0,
		"allocations" => 0
	],
	"startup" => $egg->startup,
	"description" => "",
	"deploy" => [
		"locations" => [1],
		"dedicated_ip" => false,
		"port_range" => []
	],
	"start_on_completion" => true
]);
```

**Comment by FrancoBM12** [comment]
now he just tells me, "the page does not respond"

**Comment by tyson239** [comment]
try ```$pterodactyl->servers();``` And see if it can return servers correctly. I don't think it's a problem about the ```createServer``` function. Whether it succeeds or not, it should return some data, the server infomation just created, or ```The given data failed to pass validation```.
Also try to check the log of your panel to see if the request has received by the panel.

**Comment by FrancoBM12** [comment]
the page is blank when you put $ pterodactyl-> servers (); means that if you received the data, and according to the api records when I put the $ server = $ pterodactyl-> createServer also receives it but the page says "this page does not work" so what happens?
![image](https://user-images.githubusercontent.com/36641683/60783521-9f8edf00-a110-11e9-9f28-0f31080bd61c.png)

**Comment by FrancoBM12** [comment]
that is the code that I am using

**Comment by tyson239** [comment]
```print_r($pterodactyl->servers());```

also try to use
```php
try{
	$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl(config('panel.app_key'), config('panel.url'));
	$egg = $pterodactyl->egg($pack['nest'], $pack['egg']);
	$server = $pterodactyl->createServer([
		....
	]);
	print_r($server);
}catch(\Exception $e){
	echo $e->getMessage();
}
```

**Comment by tyson239** [comment]
Remember to delete the above image or change your API_KEY as soon as possible. That image contains your API_KEY.

**Comment by FrancoBM12** [comment]
I know, look at me saying the same thing "This page does not work privatenodes.ml can not process this request at this time."

**Comment by tyson239** [comment]
or just try to get server list first to seems if it's still can't process the request?
```php
try{
	$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl('LfCA1xH9K9Gnc5VUh9ZV8xwQun2odBY7zGEStvbRLMbf3Htu', 'http://panel.privatenodes.ml/');
	$servers = $pterodactyl->servers();
	print_r($servers);
}catch(\Exception $e){
	echo $e->getMessage();
}
```
I have just tried it, and it will return:
```php
{
    "errors": [
        {
            "code": "AccessDeniedHttpException",
            "status": "403",
            "detail": "An error was encountered while processing this request."
        }
    ]
}
```

**Comment by xFrancoBM** [comment]
I just deleted that key api, this is the new "qAebqXk6Xv6eZkWoVBkMV5edpaVlqFADUfBOhgnqapZobPeY"

**Comment by tyson239** [comment]
can I use it to try to create a server?

**Comment by FrancoBM12** [comment]
yes

**Comment by tyson239** [comment]
I can get this message ```The given data failed to pass validation.```

**Comment by FrancoBM12** [comment]
and because?

**Comment by FrancoBM12** [comment]
Location id: 1, Node id: 7

**Comment by tyson239** [comment]
try to replace ```environment``` to the variables or your eggs, I can't test it properly as I can't login to your panel directly.
also you can read this document, https://deploys.io/docs/api/pterodactyl/v1/#create-server

**Comment by FrancoBM12** [comment]
http://35.199.167.18/
test@panel.com
test123
Admin Panel
Api: "KkFo2mtWJKKR6mccWKGeUnVhR1Ruk9zeEQzi0oOjpzmvlb0H"

**Comment by tyson239** [comment]
clearly works, just set the ```environment``` properly. 
```php
try{
	$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl('KkFo2mtWJKKR6mccWKGeUnVhR1Ruk9zeEQzi0oOjpzmvlb0H', 'http://35.199.167.18');
	$egg = $pterodactyl->egg(1, 4);
	$server = $pterodactyl->createServer([
		"name" => "test",
		"user" => 1,
		"egg" => 4,
		"docker_image" => $egg->dockerImage,
		"skip_scripts" => false,
		"environment" => [
			"SERVER_JARFILE" => "server.jar",
			"SPONGE_VERSION" => "1.11.2-6.1.0-BETA-21"
		],
		"limits" => [
			"memory" => 256,
			"swap" => 0,
			"disk" => 512,
			"io" => 500,
			"cpu" => 0
		],
		"feature_limits" => [
			"databases" => 0,
			"allocations" => 0
		],
		"startup" => $egg->startup,
		"description" => "",
		"deploy" => [
			"locations" => [2],
			"dedicated_ip" => false,
			"port_range" => []
		],
		"start_on_completion" => true
	]);
	print_r($server);
}catch(\Exception $e){
	echo $e->getMessage();
}
```

**Comment by FrancoBM12** [comment]
I do not know what happens, but it does not work for me

![image](https://user-images.githubusercontent.com/36641683/60785564-0dd79f80-a119-11e9-8785-1004abb39001.png)

**Comment by FrancoBM12** [comment]
keeps coming "this page does not work"

**Comment by tyson239** [comment]
Have you enabled error reporting of your PHP? Try putting this code at the top of your file.
```php
error_reporting(1);
```
just like
```php
<?php
    error_reporting(1);
    ....
?>
```

**Comment by FrancoBM12** [comment]
Which version are you using?

**Comment by tyson239** [comment]
PHP Version 7.2.8

**Comment by FrancoBM12** [comment]
PHP Version 7.2.19-0

**Comment by tyson239** [comment]
so it won't be the version issues.

**Comment by FrancoBM12** [comment]
So, what could it be ...

**Comment by tyson239** [comment]
Have you enabled error reporting?

**Comment by FrancoBM12** [comment]
yes

**Comment by tyson239** [comment]
Also are you install this sdk by composer?

**Comment by FrancoBM12** [comment]
yes

**Comment by FrancoBM12** [comment]
I say, no, I took it out of a .rar file

**Comment by FrancoBM12** [comment]
try it on localhost with xampp and get this "Fatal error: Uncaught Error: Call to undefined method HCGCloud \ Pterodactyl \ Pterodactyl :: egg () in C: \ xampp \ htdocs \ dash \ index.php: 6 Stack trace: # 0 {main} thrown in C: \ xampp \ htdocs \ dash \ index.php on line 6 "

**Comment by tyson239** [comment]
so you need to install it by composer, as there are some components required by this sdk.

**Comment by FrancoBM12** [comment]
well, and how can I make a query to know if the created user already exists ?, and apart from that how can I change the ram?

**Comment by tyson239** [comment]
just use ```$pterodactyl->userex($id);``` and check if it return the user details.
```php
function userExists($id){
	try{
		$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl(config('panel.app_key'), config('panel.url'));
		$pterodactyl->userex($id);
		return true;
	}catch(\Exception $e){
		//or by http code
		if($e->getMessage() == 'The resource you are looking for could not be found.') return false;
		return false;
	}
}
```

**Comment by tyson239** [comment]
```userex``` means you should provide an external id, which should be the identity of your own sale system.

**Comment by FrancoBM12** [comment]
and apart from that how can I change the ram?

**Comment by tyson239** [comment]
What do you mean by ram?

**Comment by FrancoBM12** [comment]
Can I change the server ram with this api?

**Comment by tyson239** [comment]
Do you mean memory?

**Comment by FrancoBM12** [comment]
if memory, I got confused

**Comment by tyson239** [comment]
```php
		"limits" => [
			"memory" => 256, //here
			"swap" => 0,
			"disk" => 512,
			"io" => 500,
			"cpu" => 0
		],
```

**Comment by FrancoBM12** [comment]
I say, from an already created server, can I modify the memory?

**Comment by tyson239** [comment]
Not now, it will be integrated later.

**Comment by FrancoBM12** [comment]
Oh, well it's fine, thank you very much I'll be waiting for that update!

**Comment by tyson239** [comment]
Just added.
```php
$server = $pterodactyl->server($YOUR_SERVER_ID);
$server->updateBuild([
  "allocation" => "1",
  "memory" => 256, //here
  "swap" => 0,
  "disk" => 512,
  "io" => 500,
  "cpu" => 0,
  "feature_limits" => [
    "databases" => 0,
    "allocations" => 0
  ]
]);
```

**Comment by FrancoBM12** [comment]
So, do I have to redownload the composer?

**Comment by tyson239** [comment]
composer update hcgcloud/pterodactyl-sdk:dev-master

**Comment by FrancoBM12** [comment]
One more question, when creating the server or after, how could you get the server ID?

**Comment by tyson239** [comment]
just check the reply of the createServer request.

**Comment by xFrancoBM** [comment]
hey, I have a doubt, because when I try to do the process of creating servers with bungeecord, I get "The given data failed to pass validation?
´´´
try{
	$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl('API', 'URL');
	$egg = $pterodactyl->egg(1, 1);
	$server = $pterodactyl->createServer([
		"name" => "test",
		"user" => 1,
		"egg" => 1,
		"docker_image" => $egg->dockerImage,
		"skip_scripts" => false,
		"environment" => [
			"BUNGEECORD_JARFILE" => "bungeecord.jar",
			"BUNGEECORD_VERSION" => "latest"
		],
		"limits" => [
			"memory" => 256,
			"swap" => 0,
			"disk" => 512,
			"io" => 500,
			"cpu" => 0
		],
		"feature_limits" => [
			"databases" => 0,
			"allocations" => 0
		],
		"startup" => $egg->startup,
		"description" => "",
		"deploy" => [
			"locations" => [1],
			"dedicated_ip" => false,
			"port_range" => []
		],
		"start_on_completion" => true
	]);
	echo('<pre>');
	print_r($server);
	echo('<pre>');
}catch(\Exception $e){
	echo $e->getMessage();
}
´´´

**Comment by FrancoBM12** [comment]
hey, I have a doubt, because when I try to do the process of creating servers with bungeecord, I get "The given data failed to pass validation?

	$egg = $pterodactyl->egg(1, 1);
	$server = $pterodactyl->createServer([
		"name" => "test",
		"user" => 1,
		"egg" => 1,
		"docker_image" => $egg->dockerImage,
		"skip_scripts" => false,
		"environment" => [
			"BUNGEECORD_JARFILE" => "bungeecord.jar",
			"BUNGEECORD_VERSION" => "latest"
		],
		"limits" => [
			"memory" => 256,
			"swap" => 0,
			"disk" => 512,
			"io" => 500,
			"cpu" => 0
		],
		"feature_limits" => [
			"databases" => 0,
			"allocations" => 0
		],
		"startup" => $egg->startup,
		"description" => "",
		"deploy" => [
			"locations" => [1],
			"dedicated_ip" => false,
			"port_range" => []
		],
		"start_on_completion" => true
	]);

**Comment by FrancoBM12** [comment]
Uhm?

**Comment by tyson239** [comment]
check the parameters. especially ```limits``` and ```environment```.

**Comment by FrancoBM12** [comment]
As?

**Comment by tyson239** [comment]
Check your parameters that match your panel configuration.

**Comment by FrancoBM12** [comment]
Yes, excuse me already fixed it, now I want to know how I can get the user ID when registering it?

**Comment by tyson239** [comment]
check the response.

**Comment by FrancoBM12** [comment]
uhm?

**Comment by FrancoBM12** [comment]
hello, well now I have two problems exactly ... I want to get the id of the server at the time of creating it to place it in database, but I do not know how I want to get the id of the user to store it in the database , you help me please?

**Comment by FrancoBM12** [comment]
Will you help me, please?

**Comment by tyson239** [comment]
```php
$server = $pterodactyl->createServer([
......
]);
print_r($server);
print_r($server["attributes"]["id"]);
```

**Comment by FrancoBM12** [comment]
So, I just put that in and it will give me the ID of the created server? What about the user? It helps me too, when registering a user I want to get their ID

**Comment by tyson239** [comment]
same way.

**Comment by FrancoBM12** [comment]
Excuse me, but at the time i write that code, it sends me only the code of print_r($server) And not of print_r($server["attributes"]["id"]);

**Comment by FrancoBM12** [comment]
Help please

**Comment by FrancoBM12** [comment]
Hey, help me please

**Comment by xFrancoBM** [comment]
Help me please

**Comment by tyson239** [comment]
$server->attributes->id

**Comment by FrancoBM12** [comment]
So, in itself put print_r($server["attributes"]["id"]); I put print_r($server->attributes->id)?

**Comment by tyson239** [comment]
try it.

**Comment by FrancoBM12** [comment]
Notice:  Trying to get property 'id' of non-object in C:\xampp\htdocs\\dash\paper.php on line 42

**Comment by 1248128477** [comment]
This is the basic usage of PHP and not this sdk's issue, you should use print_r($server); to check what returned and them access sub-arrays of it.
