### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by Nevercold** [hcgcloud/pterodactyl-sdk#2]
Hello! On Installing, its comes a out of memory Error... What i can do?
https://gist.github.com/Nevercold/b971af92cdfa080544d38c2f7660e94f

**Comment by tyson239** [comment]
https://getcomposer.org/doc/articles/troubleshooting.md#memory-limit-errors

**Comment by Nevercold** [comment]
Hey, i have fixed the Error.
Now, i have a new Error when i creating a new Server.
https://paste.dsyn.ga/Vzvj2h4QyF

**Comment by Nevercold** [comment]
new code: https://paste.dsyn.ga/s3KBFj4hn1

**Comment by tyson239** [comment]
Have you provided all environment variables?

**Comment by tyson239** [comment]
```php
    "environment": {
        "SERVER_JARFILE": "server.jar",
        //...etc
    },
```

**Comment by Nevercold** [comment]
i dont know which  environment variables i need.

**Comment by tyson239** [comment]
check you egg.

**Comment by Nevercold** [comment]
I have set all from admin/nests/egg/36/variables : https://paste.dsyn.ga/NbB9n7o4E5

The Error is the same: https://paste.dsyn.ga/eX2Tx2fPTW

**Comment by tyson239** [comment]
fill external_id or remove it.

**Comment by Nevercold** [comment]
what is external_id?

**Comment by tyson239** [comment]
$server = $pterodactyl->createServer([ "external_id" => "",

**Comment by Nevercold** [comment]
What does this attitude do?

**Comment by tyson239** [comment]
like linking to your external sales system, etc. you can use $pterodactyl->serverEx($serverExternalId); to get a server instance directly.

**Comment by Nevercold** [comment]
Ah okay, thanks!

**Comment by Nevercold** [comment]
https://paste.dsyn.ga/88Lrw253o4 i have filled it and the error is still the same

**Comment by Nevercold** [comment]
what i can do?

**Comment by tyson239** [comment]
do you have
```php
$egg = $pterodactyl->egg($nest_id, $egg_id);
```
on the top of your code?

**Comment by Nevercold** [comment]
https://paste.dsyn.ga/P48yk31ojF

**Comment by tyson239** [comment]
why you remove the `1` in `locations`?

**Comment by Nevercold** [comment]
With 1 in Location comes the Same Error

**Comment by tyson239** [comment]
replace it to your location id in the panel.

**Comment by tyson239** [comment]
It may not be 1, depends on your panel.

**Comment by tyson239** [comment]
I am closing this issue, if you have any other questions, feel free to comment again.

**Comment by Nevercold** [comment]
it still does not work

**Comment by tyson239** [comment]
there must be something wrong with your variables, not this sdk's issue.
also you can check this document, https://deploys.io/docs/api/pterodactyl/v1/#create-server
