### ISSUE TITLE
How to get it without composer?

### ISSUE THREAD

**Issue by TheKenzo** [hcgcloud/pterodactyl-sdk#21]
I want to integrate pterodactyl without composer.

**Comment by tyson239** [comment]
Hi, you can install with composer in your local machine first, then you will have the `vendor` folder, just upload it to your webserver and you can use it without composer.

**Comment by adrijanb** [comment]
Another way is to implement the Pterodactyl API yourself 👍 

Docs: https://dashflo.net/docs/api/pterodactyl/v0.7/#introduction
