### ISSUE TITLE
How to create server?

### ISSUE THREAD

**Issue by MrFallen** [hcgcloud/pterodactyl-sdk#22]
Hello. I want create TF2 server. I need example :(
Whats wrong?
![image](https://user-images.githubusercontent.com/5339386/77691180-3168b000-6ff0-11ea-85fd-e7698c3104ea.png)

**Comment by tyson239** [comment]
Hi, please check the documentation: https://hcgcloud.github.io/pterodactyl-sdk-docs/exceptions/#validationexception

**Comment by MrFallen** [comment]
> Hi, please check the documentation: https://hcgcloud.github.io/pterodactyl-sdk-docs/exceptions/#validationexception

Thank you so much! <3
