### ISSUE TITLE
No viable nodes for deployment

### ISSUE THREAD

**Issue by SonDerpy** [hcgcloud/pterodactyl-sdk#26]
`{"errors":[{"code":"NoViableNodeException","status":"400","detail":"No nodes satisfying the requirements specified for automatic deployment could be found."}]}`

This is the error I get while trying to create a server. My code: 

`$server = $pterodactyl->createServer([
            "name" => $name,
            "user" => $row["pterodactyl_userid"],
            "egg" => $egg_id,
            "docker_image" => $egg->dockerImage,
            "skip_scripts" => false,
            "environment" => [
                "SERVER_AUTOUPDATE" => '1'
            ],
            "limits" => [
                "memory" => $_POST['server_ram'],
                "swap" => 0,
                "disk" => $_POST['server_disk'],
                "io" => 500,
                "cpu" => $_POST['cpu'] * 100
            ],
            "feature_limits" => [
                "databases" => 1,
                "allocations" => 1
            ],
            "startup" => $egg->startup,
            "description" => "An server made by the client page.",
            "deploy" => [
                "locations" => [$location_id],
                "dedicated_ip" => false,
                "port_range" => []
            ],
            "start_on_completion" => true
        ]);`

The location id is valid and everything, it just doesn't want to create a server

**Comment by tyson239** [comment]
Hi, have you enabled `Allow Automatic Allocation` of nodes in this location?

**Comment by SonDerpy** [comment]
> Hi, have you enabled `Allow Automatic Allocation` of nodes in this location?

Yes, I did.

**Comment by tyson239** [comment]
Besides, you need to check whether there are unallocated allocations in the location.

**Comment by shaaslowly** [comment]
{
  "code": "NoViableNodeException",
  "status": "400",
  "detail": "No nodes satisfying the requirements specified for automatic deployment could be found."
}

Please🥲
