### ISSUE TITLE
Hey there, Could I get some help?

### ISSUE THREAD

**Issue by SonDerpy** [hcgcloud/pterodactyl-sdk#29]
So hi there, basically what I want to do while creating servers, is just print out the `{"errors":[{"code":"NoViableAllocationException","status":"400","detail":"No allocations satisfying the requirements for automatic deployment were found."}]}` and just that. How could I do that? For now I am using 
`    }catch(\HCGCloud\Pterodactyl\Exceptions\ValidationException $e){
          print_r($e->errors());

    }`

**Comment by tyson239** [comment]
Hi, make sure that you have enabled `Allow Automatic Allocation` for nodes in this location.

**Comment by SonDerpy** [comment]
> Hi, make sure that you have enabled `Allow Automatic Allocation` for nodes in this location.

Hi. I already know what to do, I am just asking how to print only that part of the code

**Comment by SonDerpy** [comment]
Also how could I get the ip from an allocation?

**Comment by Arisstath** [comment]
Basic PHP knowledge, take a look here https://www.php.net/manual/en/function.json-decode.php
