### ISSUE TITLE
Curl Response says Cloudflare captcha loading

### ISSUE THREAD

**Issue by SalmanYamin1992** [hcgcloud/pterodactyl-sdk#39]
Hello I am using this SDK to send a power action to my server. I have made the php file and when I execute it from my ubuntu machine using `php api.php` it works fine. But when I upload the project to any web server and execute it from there, It gives me a cloudflare screen with a loading sign at the center. And at the top left corner there is "Please enable cookies". I am sorry I am very new to php so I am wondering if this is a problem with the web-hosting company or with my project.

**[Note: If I use it for a different pterodactyl site, then both ubuntu machine and website host works perfectly. So I am guessing I have to somehow bypass the HCaptcha. Is there some way I can send HCaptcha accessibility cookie when sending the post request with your api?]**

**Comment by tyson239** [comment]
Hi, you can try to create a `Page Rule` on Cloudflare.
![image](https://user-images.githubusercontent.com/5617150/122880221-5d4a2100-d36c-11eb-8874-feaacb8ac1d7.png)

**Comment by SalmanYamin1992** [comment]
I think I didn't state the problem properly. I don't own the domain of the pterodactyl hosted company. I am just a client with a client API key

**Comment by SalmanYamin1992** [comment]
ok correction: **[I can only achieve what I am trying to do if i run `php api.php` from google cloud shell. But if I try to do it through my personal website or through my windows machine, it fails and gives me a cloudflare landing page.]**
