### ISSUE TITLE
Is it possible to send a console command using the Pterodactyl API?

### ISSUE THREAD

**Issue by tommyvange** [hcgcloud/pterodactyl-sdk#5]
Is it possible to send a command to a server console using the Pterodactyl API and this library?

**Comment by tyson239** [comment]
yes, use

```php
$pterodactyl->commandServer($serverIdentifier, $command);
```

or

```php
$server->command($command);
```
only works with account api key.

**Comment by tommyvange** [comment]
It worked like a charm! Thank you very much!
