### ISSUE TITLE
Server create

### ISSUE THREAD

**Issue by DAThosting** [hcgcloud/pterodactyl-sdk#7]
Hi,

nice work. I played around with your sdk and can't create servers.
`Uncaught HCGCloud\Pterodactyl\Exceptions\ValidationException: The given data failed to pass validation. in /var/www/testsite/vendor/hcgcloud/pterodactyl-sdk/src/MakesHttpRequests.php:110`

My testfile is the following:
```
require_once("vendor/autoload.php"); 
$pterodactyl = new \HCGCloud\Pterodactyl\Pterodactyl('xLm12Vhbroswc0CODE2Ds0oLrzrfAtODQoVaqWqYBWOcKDReotFv', 'http://127.0.0.1/');
$nest_id = 1;
$egg_id = 5;
$location_id = 1;
$egg = $pterodactyl->egg($nest_id, $egg_id); //get docker_image and startup directly from egg
$server = $pterodactyl->createServer([
    "external_id" => 11,
    "name" => "test",
    "user" => 1,
    "egg" => $egg_id,
    "pack" => 0,
    "docker_image" => $egg->dockerImage,
    "skip_scripts" => false,
    "environment" => [],
    "limits" => [
        "memory" => 2048,
        "swap" => 0,
        "disk" => 20000,
        "io" => 0,
        "cpu" => 100
    ],
    "feature_limits" => [
        "databases" => 0,
        "allocations" => 0
    ],
    "startup" => $egg->startup,
    "description" => "",
    "deploy" => [
        "locations" => [$location_id],
        "dedicated_ip" => false,
        "port_range" => []
    ],
    "start_on_completion" => true
]);
print_r($server);
```

My node is on 0.6.12.
I am able to create servers right in the panel.

Also I'm playing with your newly created node support, there also I got the same errors.

**Comment by tyson239** [comment]
Hi, have you replaced `nest_id`, `egg_id`, `location_id` to your panel's id?

**Comment by tyson239** [comment]
Also the environment variables of the eggs should be set too.

**Comment by DAThosting** [comment]
Yes the id's are the same on my testpanel.
Your example is based on a standard fresh installed panel I guess.
Cause all IDs are the same.

**Comment by tyson239** [comment]
try to use the following code:
```php
try {
	$servers = $pterodactyl->createServer([
		//...
	]);
}catch(\Exception $e){
	print_r($e->errors());
}
```
then you can find which parameter failed to pass the validation.

**Comment by tyson239** [comment]
my test panel is not fresh installed, the ids for me is Vanilla Minecraft eggs.
however it have two environment variables SERVER_JARFILE, VANILLA_VERSION, you should also pass them in your data array, though they have default value:

```php
"environment" => [
    "SERVER_JARFILE" => "server.jar",
    "VANILLA_VERSION" => "latest"
]
``` 

I will improve the example code later.

**Comment by DAThosting** [comment]
Got it...
externalID have to be a string...
Also IO has set between 10 and 1000.

I get node creation running, but need the keys hash from the configuration file.
Searching on the official documentation, I can't find a way to get them.
Need them to directly add a node and write the key in core.json

**Comment by tyson239** [comment]
what's the mean of key hash?

**Comment by DAThosting** [comment]
If you add a node successfully, then you have to run ether the auto-deployment or use the given config for core.json.
In this config right at the bottom there is a "keys".
How I get this via API?
Or how it is created.

**Comment by tyson239** [comment]
you mean the auto deploy of a server? I think it is unnecessary to get the keys of a daemon, it's just for the communication between panel and daemon, also you should not be able get this via api.

**Comment by tyson239** [comment]
if you mean editing this:
![image](https://user-images.githubusercontent.com/5617150/70612888-b34feb80-1c42-11ea-8e8c-5fd83d8ae5ee.png)
 you can check https://dashflo.net/docs/api/pterodactyl/v1/#edit-node, as our documentation about node is not finished yet. It's called `public` in api.
![image](https://user-images.githubusercontent.com/5617150/70613231-3ec97c80-1c43-11ea-9a40-d391412cc406.png)

**Comment by DAThosting** [comment]
Short automatic procedure:
1. creating dedicated server via a api from my hoster
2. installing the os and pterodactyl daemon
3. creating node via your api

Now I have to link the panel with my node.
The only missing thing is this key to get it run without problems.

**Comment by tyson239** [comment]
I think the api can't do this, you need to install it manually.

**Comment by DAThosting** [comment]
Hm, I'll create a issue at pterodactyl directly.

Thank you anyway.
Works perfect with your sdk!

**Comment by tyson239** [comment]
I checked the panel routes just now, it seems that only this route can get the token:
https://github.com/pterodactyl/panel/blob/39f1392eee10d3256c793dba1ec9e2b5f3daefdf/routes/admin.php#L154

Requested when the clicking `Generate Token` from the admin control of the panel.
![image](https://user-images.githubusercontent.com/5617150/70614101-dda2a880-1c44-11ea-85d9-a74af2ab1308.png)

**Comment by DAThosting** [comment]
https://github.com/pterodactyl/panel/issues/1632

Same feature request already asked :D

**Comment by MrFallen** [comment]
Hello! 
I want create TF2 server.
Whats wrong?
![image](https://user-images.githubusercontent.com/5339386/77689472-6de6dc80-6fed-11ea-9820-397ad47c7644.png)
